name: React CI

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [20.x, 22.x]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Print environment variables
              run: |
                  echo "VITE_API_KEY=${{ secrets.VITE_API_KEY }}"
                  echo "VITE_AUTH_DOMAIN=${{ secrets.VITE_AUTH_DOMAIN }}"
                  echo "VITE_PROJECT_ID=${{ secrets.VITE_PROJECT_ID }}"
                  echo "VITE_STORAGE_BUCKET=${{ secrets.VITE_STORAGE_BUCKET }}"
                  echo "VITE_MESSAGING_SENDER_ID=${{ secrets.VITE_MESSAGING_SENDER_ID }}"
                  echo "VITE_APP_ID=${{ secrets.VITE_APP_ID }}"

            - name: Run vitest tests
              run: npm run test
              env:
                  VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
                  VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
                  VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
                  VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
                  VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
                  VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
                  VITE_MAPBOX_KEY: ${{ secrets.VITE_MAPBOX_KEY }}
                  VITE_API_URL: ${{ secrets.VITE_API_URL }}

            - name: Run eslint
              run: npm run lint
              env:
                  VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
                  VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
                  VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
                  VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
                  VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
                  VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
                  VITE_MAPBOX_KEY: ${{ secrets.VITE_MAPBOX_KEY }}
                  VITE_API_URL: ${{ secrets.VITE_API_URL }}
